import type { Lang } from '../i18n';

/** Words printed inside generated images. Kept apart from chat copy in i18n/. */
const pl = {
  balance: 'Saldo',
  credits: 'Kredyty',
  level: 'Poziom',
  games: 'Gry',
  winRate: 'Skuteczność',
  biggestWin: 'Rekord',
  wagered: 'Obstawione',
  streak: 'Seria daily',
  achievements: 'Osiągnięcia',
  globalRank: 'Ranking',
  days: (n: number) => (n === 1 ? '1 dzień' : `${n} dni`),
  xpToNext: (xp: string, req: string) => `${xp} / ${req} XP`,
  dealer: 'Krupier',
  you: 'Ty',
  tablePrint: 'Blackjack wypłaca 3 do 2  ·  krupier dobiera do 16, staje na 17',
  win: 'Wygrana',
  loss: 'Przegrana',
  push: 'Remis',
  bust: 'Fura',
  blackjack: 'Blackjack',
  doubled: 'Podwojone',
  crashed: 'Crash',
  cashedOut: 'Wypłacono',
  climbing: 'Mnożnik rośnie',
  crashAt: (m: string) => `Crash przy ${m}`,
  bettingOpen: 'Przyjmujemy zakłady',
  startsIn: (s: number) => `Start za ${s} s`,
  players: 'Gracze',
  noPlayers: 'Nikt jeszcze nie postawił',
  dailyTitle: 'Dzienny bonus',
  dayN: (n: number) => `Dzień ${n}`,
  nextReset: 'Reset o północy',
  leaderboard: 'Ranking graczy',
  serverLeaderboard: 'Ranking serwera',
  dropTitle: 'Na stole leży',
  dropHint: (symbol: string) => `Kliknij przycisk z symbolem ${symbol}`,
  dropClaimedBy: (name: string) => `Zgarnia ${name}`,
  dropExpired: 'Nikt nie zdążył',
  jackpotTitle: 'Royal Jackpot',
  jackpotDraw: 'Losowanie',
  jackpotTickets: 'Bilety w puli',
  jackpotYours: 'Twoje bilety',
  jackpotChance: 'Szansa',
  jackpotWinner: 'Zwycięzca',
  bigWin: 'Wielka wygrana',
  multiplier: 'Mnożnik',
  welcomeTitle: 'RoyalCasino jest na serwerze',
  welcomeSteps: [
    'Admin ustawia kasyno: /ustawienia-serwera',
    'Każdy gracz zaczyna z $5 000',
    'Wszystkie gry w jednym miejscu: /kasyno',
  ],
  vip: 'Status',
  rakeback: 'Cashback',
  season: 'Sezon',
  wins: 'Wygrane',
  roundNo: (n: number) => `Runda #${n}`,
};

export type RenderLabels = typeof pl;

const en: RenderLabels = {
  balance: 'Balance',
  credits: 'Credits',
  level: 'Level',
  games: 'Games',
  winRate: 'Win rate',
  biggestWin: 'Best win',
  wagered: 'Wagered',
  streak: 'Daily streak',
  achievements: 'Achievements',
  globalRank: 'Rank',
  days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
  xpToNext: (xp: string, req: string) => `${xp} / ${req} XP`,
  dealer: 'Dealer',
  you: 'You',
  tablePrint: 'Blackjack pays 3 to 2  ·  dealer draws to 16, stands on 17',
  win: 'Win',
  loss: 'Loss',
  push: 'Push',
  bust: 'Bust',
  blackjack: 'Blackjack',
  doubled: 'Doubled',
  crashed: 'Crashed',
  cashedOut: 'Cashed out',
  climbing: 'Multiplier climbing',
  crashAt: (m: string) => `Crashed at ${m}`,
  bettingOpen: 'Bets are open',
  startsIn: (s: number) => `Starts in ${s}s`,
  players: 'Players',
  noPlayers: 'No bets yet',
  dailyTitle: 'Daily bonus',
  dayN: (n: number) => `Day ${n}`,
  nextReset: 'Resets at midnight',
  leaderboard: 'Leaderboard',
  serverLeaderboard: 'Server leaderboard',
  dropTitle: 'On the table',
  dropHint: (symbol: string) => `Press the button with ${symbol}`,
  dropClaimedBy: (name: string) => `${name} takes it`,
  dropExpired: 'Nobody was fast enough',
  jackpotTitle: 'Royal Jackpot',
  jackpotDraw: 'Draw',
  jackpotTickets: 'Tickets in pot',
  jackpotYours: 'Your tickets',
  jackpotChance: 'Chance',
  jackpotWinner: 'Winner',
  bigWin: 'Big win',
  multiplier: 'Multiplier',
  welcomeTitle: 'RoyalCasino has joined',
  welcomeSteps: [
    'Admins set things up: /server-settings',
    'Every player starts with $5,000',
    'Every game in one place: /casino',
  ],
  vip: 'Status',
  rakeback: 'Cashback',
  season: 'Season',
  wins: 'Wins',
  roundNo: (n: number) => `Round #${n}`,
};

export function labels(lang: Lang): RenderLabels {
  return lang === 'en' ? en : pl;
}
